####
_USELESSBOX_					= Box(MENU, width=10, height=5, align="right")
MENU_firstwhite					= Box(MENU, width=mainbox.tk.winfo_width()-215, height=mainbox.tk.winfo_height()-75, align="right")
MENU_firstwhite.bg				= "#FFFFFF"
_USELESSBOX_					= Box(MENU_firstwhite, width="fill", height=10)
MENU_backdrop					= Box(MENU_firstwhite, width=mainbox.tk.winfo_width()-235, height=mainbox.tk.winfo_height()-95)
MENU_backdrop.bg				= "#E6E1C1"
_USELESSBOX_					= Box(MENU_backdrop, width="fill", height=10)
MENU_main						= Box(MENU_backdrop, width=MENU_backdrop.width-20, height=MENU_backdrop.height-20, border=True)
MENU_main.bg					= "#FFFFFF"
_USELESSBOX_					= Box(MENU_main, width=MENU_main.width, height=5)
_MENUTOPBAR_					= Box(MENU_main, width=MENU_main.width, height=30)
_MENUTOPBAR_.bg					= "#BFBFBF"
MENU_title						= Text(_MENUTOPBAR_, width="fill", height="fill")
_USELESSBOX_					= Box(MENU_main, width="fill", height=2)
_USELESSBOX_					= Box(MENU, width=10, height="fill", align="left")
MENU_wafflelist					= Box(MENU, width=mainbox.tk.winfo_width()-525, height=mainbox.tk.winfo_height()-75, align="left")
MENU_wafflelist.bg				= "#FFFFFF"
#
_MENU_accountsettingsbox_		= Box(MENU_wafflelist, width="fill", height=20)
_MENU_accountsettings_			= Text(_MENU_accountsettingsbox_, text="Account Settings")
MENU_passemailbox				= Box(MENU_wafflelist, width=mainbox.tk.winfo_width()-535, height=195, border=True)
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_currentpassbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_currentpass			= TextBox(_SETTINGS_currentpassbox_, width="fill", height="fill", placeholder="CURRENTP")
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_newpasswordbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_newpass				= TextBox(_SETTINGS_newpasswordbox_, width="fill", height="fill", placeholder="NEWP")
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_confirmpassbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_confirmpass			= TextBox(_SETTINGS_confirmpassbox_, width="fill", height="fill", placeholder="CONFIRMP")
_SETTINGS_changepasswordbox_	= Box(MENU_passemailbox, width=165, height=25)
SETTINGS_changepassword			= PushButton(_SETTINGS_changepasswordbox_, width="fill", height="fill", text="CHANGE PASSWORD", command=commandsorter.get("CHANGEpassword"))
SETTINGS_changepassword.bg		= "#D8D8D8"
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_currentemailtextbox_	= Box(MENU_passemailbox, width=165, height=16)
SETTINGS_currentemailtext		= Text(_SETTINGS_currentemailtextbox_, width="fill", height="fill", size=8)
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_newemailbox_			= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_newemail				= TextBox(_SETTINGS_newemailbox_, width="fill", height="fill", placeholder="NEWE")
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_confirmemailbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_confirmemail			= TextBox(_SETTINGS_confirmemailbox_, width="fill", height="fill", placeholder="CONFIRME")
_SETTINGS_changeemailbox_		= Box(MENU_passemailbox, width=165, height=25)
SETTINGS_changeemail			= PushButton(_SETTINGS_changeemailbox_, width="fill", height="fill", text="CHANGE EMAIL", command=commandsorter.get("CHANGEemail"))
SETTINGS_changeemail.bg			= "#D8D8D8"
SETTINGS_currentpass.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_currentpass, str(type), True))
SETTINGS_currentpass.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_currentpass, str(type), True))
SETTINGS_newpass.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_newpass, str(type), True))
SETTINGS_newpass.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_newpass, str(type), True))
SETTINGS_confirmpass.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_confirmpass, str(type), True))	
SETTINGS_confirmpass.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_confirmpass, str(type), True))
SETTINGS_newemail.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_newemail, str(type), False))
SETTINGS_newemail.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_newemail, str(type), False))
SETTINGS_confirmemail.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_confirmemail, str(type), False))
SETTINGS_confirmemail.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_confirmemail, str(type), False))
