_MENU_accountsettingsbox_		= Box(MENU_wafflelist, width="fill", height=20)
_MENU_accountsettings_			= Text(_MENU_accountsettingsbox_, text="Account Settings")
MENU_passemailbox				= Box(MENU_wafflelist, width=mainbox.tk.winfo_width()-535, height=195, border=True)
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_currentpassbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_currentpass			= TextBox(_SETTINGS_currentpassbox_, width="fill", height="fill", placeholder="CURRENTP")
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_newpasswordbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_newpass				= TextBox(_SETTINGS_newpasswordbox_, width="fill", height="fill", placeholder="NEWP")
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_confirmpassbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_confirmpass			= TextBox(_SETTINGS_confirmpassbox_, width="fill", height="fill", placeholder="CONFIRMP")
_SETTINGS_changepasswordbox_	= Box(MENU_passemailbox, width=165, height=25)
SETTINGS_changepassword			= PushButton(_SETTINGS_changepasswordbox_, width="fill", height="fill", text="CHANGE PASSWORD", command=commandsorter.get("CHANGEpassword"))
SETTINGS_changepassword.bg		= "#D8D8D8"
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_currentemailtextbox_	= Box(MENU_passemailbox, width=165, height=16)
SETTINGS_currentemailtext		= Text(_SETTINGS_currentemailtextbox_, width="fill", height="fill", size=8)
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_newemailbox_			= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_newemail				= TextBox(_SETTINGS_newemailbox_, width="fill", height="fill", placeholder="NEWE")
_USELESSBOX_					= Box(MENU_passemailbox, width="fill", height=2)
_SETTINGS_confirmemailbox_		= Box(MENU_passemailbox, width=165, height=22)
SETTINGS_confirmemail			= TextBox(_SETTINGS_confirmemailbox_, width="fill", height="fill", placeholder="CONFIRME")
_SETTINGS_changeemailbox_		= Box(MENU_passemailbox, width=165, height=25)
SETTINGS_changeemail			= PushButton(_SETTINGS_changeemailbox_, width="fill", height="fill", text="CHANGE EMAIL", command=commandsorter.get("CHANGEemail"))
SETTINGS_changeemail.bg			= "#D8D8D8"
SETTINGS_currentpass.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_currentpass, str(type), True))
SETTINGS_currentpass.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_currentpass, str(type), True))
SETTINGS_newpass.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_newpass, str(type), True))
SETTINGS_newpass.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_newpass, str(type), True))
SETTINGS_confirmpass.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_confirmpass, str(type), True))	
SETTINGS_confirmpass.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_confirmpass, str(type), True))
SETTINGS_newemail.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_newemail, str(type), False))
SETTINGS_newemail.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_newemail, str(type), False))
SETTINGS_confirmemail.tk.bind("<FocusIn>", lambda type: placeholderfunc(SETTINGS_confirmemail, str(type), False))
SETTINGS_confirmemail.tk.bind("<FocusOut>", lambda type: placeholderfunc(SETTINGS_confirmemail, str(type), False))
